CREATE TABLE IF NOT EXISTS tracking_search (
  id INT AUTO_INCREMENT PRIMARY KEY,
  keyword VARCHAR(255) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  user_agent VARCHAR(255) NOT NULL,
  search_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);